name: 🐛 Bug Report
description: File a bug report
title: "[BUG]: "
labels: [🐛 bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug. Also, please tell us what you expected to happen.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please explain in detail how to recreate the bug.
    validations:
      required: true
  - type: input
    id: storybook-demo
    attributes:
      label: Storybook Demonstration
      description: Bugs that are recreated in Storybook will be prioritized. Please recreate your bug in a story or stories on a new branch starting with "bug-" and provide the url here.
      placeholder: "https://vimeo.github.io/iris/sb/bug-BRANCH/?path=/story/PATH-TO-STORY"
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Iris are you using?
      placeholder: "0.104.0"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: After submitting your issue, please edit your post to add any relevant screenshots, gifs, or videos.
      placeholder: Edit your issue after posting to add screenshots.      
    validations:
      required: false
